$engine: 3
$onesync: on

name: vMenu
author: Tom Grobbe
description: A custom server sided trainer/menu for FiveM, including full permission support.

tasks:
  # Download default resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources

  - action: remove_path
    path: ./resources/[gameplay]/chat

  - action: remove_path
    path: ./resources/[system]/[builders]

  # Download server.cfg
  - action: download_file
    url: https://raw.githubusercontent.com/feelfreetofee/vMenu-recipe/main/server.cfg
    path: ./server.cfg

  # Download vMenu
  - action: download_file
    path: ./tmp/vmenu.zip
    url: https://github.com/TomGrobbe/vMenu/releases/download/v3.8.61/vMenu-3.8.61.zip

  - action: unzip
    dest: ./resources/[local]/vMenu
    src: ./tmp/vmenu.zip

  # Cleanup
  - action: remove_path
    path: ./tmp
